("TSZ.DGO"
  (
  "static-screen.o"
  "WrongBoneVisualsMisaligned-ag.go"
  "WrongBoneVisualsAligned-ag.go"
  "MultipleMaterials-ag.go"
  "AttachToDaxter-ag.go"
  "test-zone-obs.o"
  "test-zone.go"
  )
)
